### PR TITLE
Adds axios post and fixes the login error

### PR DESCRIPTION
**Pull request by bdougie**
#31 Was closed but it started a trend that fixes the Api calls to the Bloc Api.

# What is this?

Login has been broken for a week and seems like the request being made by `fetch()` aren't cutting anymore.

Basically the `JSON.parse(res._bodyText)` are not working anymore. I have the `[axios](https://github.com/mzabriskie/axios)` to do the fetch and JSON parsing in one function. I was trying to avoid adding a dependency to just pull in data, but this seems a bit necessary. 

# Please review

```
$ git fetch
$ git checkout fix-api-auth
```

### CODE REVIEW

**Comment by ajalger** [comment]
@bdougie I will have to play with this because it doesn't give back anything still. Also, you will have to fix the response status. It should be `res.ok` not `res.status.ok`. `res.status` gives you a number back, while `res.ok` just gives you the boolean.

**Comment by ajalger** [comment]
@bdougie 
See now pull request #47. We don't need axios.

**Comment by bdougie** [comment]
Nice, I am going to run this locally shortly

**Comment by bdougie** [comment]
I get this: 

```
console.log(res.status.ok)
=> undefined

```

**Comment by ajalger** [comment]
You will get `undefined` because `res.status.ok` doesn't work. You have to use `res.ok` instead. However, since you're not using `fetch` that won't work because axios has a different API.

**Comment by ajalger** [comment]
Sorry, but this merge does not allow me to login and view messages.

**Comment by bdougie** [comment]
moving conversation to #47

**Pull request merged**
