### PR TITLE
added .vscode to gitignore

### PR DESCRIPTION
**Pull request by ajalger**
These are some suggestions for the code style.

### CODE REVIEW

**Comment by dpaola2** [comment]
Looks good to me 👍

**Comment by bdougie** [comment]
@ajalger have you already started poking around with Android?

**Comment by ajalger** [comment]
Not yet

**Comment by bdougie** [comment]
ok just curious about what vscode is

**Comment by ajalger** [comment]
Visual studio code. It's like Sublime but has more options. https://code.visualstudio.com/

**Comment by bdougie** [comment]
good to know

**Pull request merged**
